
development:
  adapter: postgresql
  database: anagram_development
  encoding: unicode
  username: 
  password: 
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: anagram_test
  encoding: unicode  
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: anagram_production
  encoding: unicode
  pool: 5
  timeout: 5000
